audio:
  format:
    sampleRate: 48000
    sampleSizeInBits: 16
    channels: 2
  buffer:
    sizeInSeconds: 16
  window:
    default: 'BLACKMAN'
  representation:
    spectrogram:
      color:
        black_dBFS: -70
        white_dBFS: -23
      log2FFTLength:
        max: 15
        min: 9
        value: 14
      overlappingCoefficient:
        max: 100
        min: 5
        value: 10
      lowPassFilter:
        max: 20000
        min: 0
        value: 7000
view:
  ui:
    width: 1280
    height: 720
    renderWidth: 1920
    renderHeight: 32768
  fps: 90




